name: Generar Sitemap y Robots.txt Automático

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate sitemap and robots.txt
    steps:
    - name: Checkout el código
      uses: actions/checkout@v4

    - name: Crear el archivo Sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://dadapoetry.cat
        
    - name: Crear el archivo robots.txt de forma automática
      run: |
        echo "User-agent: *" > robots.txt
        echo "Disallow: /admin/" >> robots.txt
        echo "Disallow: /config/" >> robots.txt
        echo "" >> robots.txt
        echo "Sitemap: https://dadapoetry.cat/sitemap.xml" >> robots.txt

    - name: Hacer commit y push de los archivos generados
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml robots.txt
        git commit -m "Automated sitemap and robots.txt update" || exit 0
        git push
